package com.gmail.seanduffy797.dungeon;

public enum DungeonItem {

    TELEPORT_PEARL,
    VINDICATORS_AXE,
    HUSK_LEATHER_HAT,
    HUSK_LEATHER_TUNIC,
    HUSK_LEATHER_PANTS,
    HUSK_LEATHER_BOOTS,
    SKELETON_LEATHER_HAT,
    SKELETON_LEATHER_TUNIC,
    SKELETON_LEATHER_PANTS,
    SKELETON_LEATHER_BOOTS
}
